### ISSUE TITLE
OnClose event

### ISSUE THREAD

**Issue by egorzot** [rawilk/vue-context#10]
### Description
Maybe It would be better if  we have an OnClose event to handle menu closing?

```
close () {
  this.top = null;
  this.left = null;
  this.data = null;
  this.show = false;
  this.$emit('close');
},
```

**Comment by rawilk** [comment]
Good idea, I will implement this sometime when I get a chance to.

**Comment by egorzot** [comment]
@rawilk can I send PR ?

**Comment by rawilk** [comment]
@egorzot - Thanks, but I already have the changes implemented since it was a small change. See PR #11.

**Comment by rawilk** [comment]
I did also add in the ability to listen for an `open` event on the menu in version 3.3.0, as I'm sure you'll see in the PR I made.

**Comment by egorzot** [comment]
@rawilk thanks :+1: :+1:
