### ISSUE TITLE
Use of clickaway removes ability to open a context menu with a left click

### ISSUE THREAD

**Issue by robjbrain** [rawilk/vue-context#14]
### Description

Obviously the main purpose of this package is to allow for a right click to open a contextmenu.

However it should in theory work for left clicks as well.

I thought this would be a simple case of replacing `@contextmenu` with `@click`.

However I found that clickaway is detecting the click and closing the context menu instantly.

Removing `v-on-clickaway` allows for a left click context menu but obviously the context menu just stays open indefinitely.

I also tested the old branch that used `@blur` and a left click was possible. So removing this ability may have been an unintentional side effect of using clickaway.

I haven't been able to figure out a way to fix this yet.

**Comment by Romick2005** [comment]
Hi I think all you need to do is just to play with .stop .prevent click event modifiers.
I have updated code little bit to feet my need but the main logic should be the same.
You can check it [here](https://jsfiddle.net/cdxjqgk5 ).
So basically it is context menu and you can specify wrapper container when it will appear and also provide left or right mouse click events to capture.
In my example just for demo it should show context menu on both left and right mouse click.
Hope this helps.

**Comment by rawilk** [comment]
@robjbrain You should be able to use the `stop` modifier as suggested by @Romick2005 on the left click event to fix that issue. I've tested it with and without modifiers on the `@click` event and it worked without issue for me, so there must be something in your code that is causing it to happen.

Sorry for not responding sooner, I've been busy with other projects and haven't had a chance to maintain this one until now.

**Comment by rawilk** [comment]
I've also added some information about left clicks to the README for others who may have similar issues: https://github.com/rawilk/vue-context#left-click-support

**Comment by joaopedromago** [comment]
Worked for me only when i put `lazy` prop on `vue-context` element.

See my code below:

```vue
<template>
  <div>
    <v-btn :icon="icon" @click.prevent="$refs.menu.open($event)">
      <slot />
    </v-btn>

    <vue-context ref="menu" lazy>
      <li v-for="option in options" :key="option.text">
        <a @click.prevent="option.event">
          {{ option.text }}
        </a>
      </li>
    </vue-context>
  </div>
</template>

<script>
import VueContext from "vue-context";
import "vue-context/src/sass/vue-context.scss";

export default {
  components: { VueContext },
  props: {
    options: Array,
    icon: Boolean
  }
};
</script>
```
