### ISSUE TITLE
Close other existing context-menu when right-clicking

### ISSUE THREAD

**Issue by GregoryWullimann** [rawilk/vue-context#15]
Hi,

I'm using the context-menu in multiple equal components. The is a small issue:

When I open the context-menu on one component and then right-click on another component the previous menu stays open.

What I could do is that every time time a new menu is open an event is emitted to all other components and close the other menus, but this solution doesn't seems really practical.

Is there another way?

**Comment by rawilk** [comment]
Could you show some code of how you're using the menu?

**Comment by neelspatel** [comment]
I'm having the issue, here's an outline of what my code looks like:

component_with_context_menu:

```
<template>
  <div @contextmenu.prevent="$refs.menu.open">
    <vue-context ref="menu" v-bind:key="word.key + 'menu'">
        <ul class="list-group context-menu-list">
            <li>...</li>
        </ul>
    </vue-context>
    <div>Other parts of the component go here</div>
  </div>
</template>
```


Parent component:

`<component_with_context_menu v-for="value in list"></component_with_context_menu>`

**Comment by rawilk** [comment]
@neelspatel Typically you are going to need to place the context menu outside of the element that has the `@contextmenu` event on it. In your case, I would do something like this:

```html
<template>
   <div>
         <vue-context ref="menu">
               <ul>
                    <li>...</li>
               </ul>
         </vue-context>
         <div @contextmenu.prevent="$refs.menu.open">Other parts of component_with_context_menu go here</div>
   </div>
</template>
```

Also, are you using the **latest** version of vue-context?
