### ISSUE TITLE
Add keyboard support

### ISSUE THREAD

**Issue by ChuckFields** [rawilk/vue-context#21]
### Description

Most context menus allow using the up and down arrows to change the selected context menu item as well as using the enter key to select the selected item.

**Comment by rawilk** [comment]
@ChuckFields I haven't really taken that into consideration but it sounds like it would be a useful feature for the context menu to have. I'm not sure when I'll get a chance to work on the menu next, but this is something I'll definitely consider implementing.

**Comment by rawilk** [comment]
@ChuckFields 

I just released version `4.0.0` of the context menu. This will allow keyboard navigation of the up and down arrows, as well as closing the menu via the `esc` key.

Also I have also updated the html structure and styling slightly of the context menu, so keep that in mind if you update the package as you may need to adjust your context menu implementations accordingly. These changes will be documented soon as well.

**Comment by ChuckFields** [comment]
@rawilk That was quick! Thank you - we will test it out.

**Comment by ChuckFields** [comment]
@rawilk After some minor adjustments to how we've implemented the context menu, everything seems to be working great. Thanks again.
