### ISSUE TITLE
@close does not fire when and item is selected

### ISSUE THREAD

**Issue by ChuckFields** [rawilk/vue-context#23]
### Description
@close does not fire when the context menu is closed via selecting an item with the mouse or with the keyboard.

### Version

4.0.0

**Comment by rawilk** [comment]
I will look into this

**Comment by rawilk** [comment]
@ChuckFields 

After looking at it, I forgot that I had a conditional in there when I first implemented this. Apparently it was emitting the `close` event twice for some reason when I first did that so I just elected to not emit it on click events. 

After playing around with it, it seems that's not the case anymore and now I've dropped that conditional and updated the package. If you update to version `4.0.1` it should always emit the the `close` event now for you anytime the menu is closed.

**Comment by ChuckFields** [comment]
@rawilk Works perfectly, thank you. I'll close this issue.
