### ISSUE TITLE
Context menu does not auto close when inside of a popover

### ISSUE THREAD

**Issue by ChuckFields** [rawilk/vue-context#24]
### Description

I'm using the popover in [ElementUI](https://element.eleme.io/#/en-US), which uses[ popper.js](https://popper.js.org/). When I put a vue-context menu inside of the popper, it does not close if i click somewhere else in the popover.

### Steps to Reproduce
[https://codesandbox.io/s/vue-template-g80uj](https://codesandbox.io/s/vue-template-g80uj)
1. Click on the button to open the popover
2. Right click on the text
3. Click on the text below, or anywhere else on the popover

**Expected behavior:**
The vue-context menu to close

**Actual behavior:**
It stays open

**Reproduces how often:**
100%

### Version
4.0.1

**Comment by rawilk** [comment]
@ChuckFields Thank you for providing an example for me to look at. After looking at it, I'm not really sure what the issue could be but I will try to figure it out.
