### ISSUE TITLE
LocalItemSelector data doesn't update when itemSelector prop does

### ISSUE THREAD

**Issue by Jakob-Maudience** [rawilk/vue-context#30]
## Description

I'm having an issue where I want to dynamically update the item selector in the component under certain conditions (I have a submenu in my context menu, and when it's open, I only want the keyboard nav to cycle through the sub menu items, which have a different class)

As you can see in the cache, the itemSelector property gets updated by the parent component, but the internal localItemSelector data remains cached, and doesn't update.

![2019-07-26_11-39-36](https://user-images.githubusercontent.com/24442559/61967122-32959900-af9a-11e9-9e11-e6345651629d.gif)

This prevents the keyboard navigation from cycling through the elements I need under those conditions.

### Steps to Reproduce

1. In the parent component, add a computed property that is set to different classnames under different conditions. Here's my code:
```js
contextItemSelector() {
     return this.subMenuOpen ? '.context-option--submenu' : '.context-option';
 },
```
2. Set the itemSelector property on the vue-context component to the computed property
```html
<vue-context ref="menu" :item-selector="contextItemSelector">
```

**Expected behavior:** I expect the class selector to update

**Actual behavior:** The component gets the initial state, but doesn't update.

**Reproduces how often:** 100% of the time
### Version 
Package : 4.0.1
Browser: Chromium (Electron)

**Comment by rawilk** [comment]
@Jakob-Maudience Thank you for reporting the issue. I have released a new version of the menu (4.0.3) that addresses this issue. If you have further issues with this, please let me know and I can look into it.

**Comment by Jakob-Maudience** [comment]
Thanks for the quick update. I'll update my package and let you know if I run into any issues.

**Comment by rawilk** [comment]
Since I haven't heard anything else on this issue, I'm going to consider it closed. If you have any other issues with it, feel free to re-open this issue.
