### ISSUE TITLE
Two context menu components - old one not closing on open

### ISSUE THREAD

**Issue by Zireael** [rawilk/vue-context#31]
Hi,
Might be an edge case, but I thought I'll let you know.
If there are two menu components on the same page:
```
<VueContext ref="menu1"></VueContext>
<VueContext ref="menu2"></VueContext>
```
If you right click on an element to open` menu1`, and then go and click on something else to open `menu2`, the `menu1` remains open. Expected (intuitive) behavior would be for old menu to close.

Also, with either or both menus open, if you right-click on an element that is not handled by `vue-context` (you get default browser right-menu), the `vue-context` menus remain open. Expected (intuitive) behavior would be for `vue-context` menu(s) to close.

Thanks for making the component!

**Comment by gamazu** [comment]
You can implement it yourself. Just manually close the other context menu.
```
methods:{
	showCtxOne(){
		this.$refs.menu2.close()
		this.$refs.menu1.open()
	},
	showCtxTwo(){
		this.$refs.menu1.close()
		this.$refs.menu2.open()
	}
}
```
