### ISSUE TITLE
Not working with Nuxt

### ISSUE THREAD

**Issue by Torone** [rawilk/vue-context#32]
NOTE: ISSUES ARE NOT FOR CODE HELP - Ask for help at 
https://stackoverflow.com

### Description

As per title, not working with Nuxt. It works fine unless you refresh the page. Once the page is refreshed it crash with error: "Window is not defined". I tried using it as suggested by you and also as suggested by Nuxt, including it in the plugins section. Nothing...

### Steps to Reproduce

1. Install it with nuxt
2. refresh the page where you are using the plugin
3. please suggest a fix

**Expected behavior:** The app should not crash on page refresh

**Actual behavior:** It crash on page refresh

**Reproduces how often:** Every time. 100%.

### Additional Information /

**Comment by rawilk** [comment]
@Torone Sorry for the late response, I've been very busy with other projects lately and haven't had much time for my open source ones... 

Have you tried only importing the menu on the client side, i.e. with the `process.client` variable? https://nuxtjs.org/faq/window-document-undefined/

If that doesn't work, I'm not sure what else I'd be able to do on my end to fix this.
