### ISSUE TITLE
Menu is misaligned if parent using CSS transform

### ISSUE THREAD

**Issue by 2-5** [rawilk/vue-context#34]
The menu is not aligned properly if the parent element is positioned using CSS transform. For example when using a modular layout system - https://jbaysolutions.github.io/vue-grid-layout/examples/01-basic.html

**Comment by rawilk** [comment]
See #36

**Comment by Affecomia** [comment]
@rawilk I don't see how the inclusion of the css instead of the scss/sass file would make a difference of the misalignment issue? I have the same issue, and have so far been unable to find a solution.
