### ISSUE TITLE
npm install can't be styled

### ISSUE THREAD

**Issue by 2-5** [rawilk/vue-context#36]
If you install `vue-context` using `npm`, it's not possible to style it.

The styling is baked in `dist/index.js`, and the `SASS` files are not included (due to `.npmignore`)

**Comment by rawilk** [comment]
This should be fixed now - see #38.

If you use sass, you can import the menu's styles like so:

```bash
@import '~vue-context/dist/css/vue-context.css';
```

From there, you should be able to style the menu as needed. I think this should resolve the other styling issue you created which seems to be related to this as now you should be able to style the menu as your needs dictate.
