### ISSUE TITLE
Window scrolls on activating context menu

### ISSUE THREAD

**Issue by Dylan-DutchAndBold** [rawilk/vue-context#4]
### Description

The window scrolls when context menu shows

### Steps to Reproduce

1. I actually have two divs. One with a height of say `50px` and a div that has an height of `calc(100vh - 50px)`
2. Then I have a table with height of `100%` inside that second div which activates the context menu on row click
3. This behaviour appears in these circumstances

**Expected behavior:**

Do not scroll

**Actual behavior:**

The window scrolls

Can be seen here:
https://gyazo.com/f78f5eaa2b03eeef4b8d0af2e52bb1f0

### Version

`"vue-context": "^3.1.0",`

**Comment by Dylan-DutchAndBold** [comment]
I'd like to add here, that the windows scrolls that exact `50px`

**Comment by rawilk** [comment]
@Dylan-DutchAndBold 

Thank you for submitting this but unfortunately I can't seem to replicate this on my end. I have committed a file that I was using to replicate this here: https://github.com/rawilk/vue-context/blob/master/test/test_issue_4.html

I would like to be able to resolve this for you so if you could look at the file and point me in the direction  of how to better replicate the issue that would be appreciated.

**Comment by Dylan-DutchAndBold** [comment]
@rawilk Thanks, will get back to you after the weekend.

**Comment by Dylan-DutchAndBold** [comment]
I have been puzzling with your test and I was in no way able to replicate the issue. I have very strong feelings that the framework I use (elementui) applies some auto sizing magic which does this. Setting the calculated height (100%-nav) directly on the div which is parent of the table fixed the issue on my end. So I'm sorry for assuming the issue was with your context menu. Keep up the great work. It's definitely appreciated!

**Comment by rawilk** [comment]
@Dylan-DutchAndBold 

It's not a problem. I'm glad it is working now as intended on your end.
