### ISSUE TITLE
Why not exporting as default when there's no need to use destructuring 

### ISSUE THREAD

**Issue by tripflex** [rawilk/vue-context#41]
First, thank you for all your work on this lib, it is greatly appreciated 👍 

https://github.com/rawilk/vue-context/blob/39adea968ad85957ab5285b909a999fc2fd2cc90/src/js/index.js#L1

Why not just export this as default instead of making it so that we have to use destructuring to import it?

Reason I ask is if we are doing code splitting it requires more code, when it could just be exported as default since there's nothing else being exported (so even tree shaking wouldn't matter in this situation)
https://github.com/rawilk/vue-context/issues/33#issuecomment-545623173

This could be both a named export and default export (to maintain backwards compatibility)

**Comment by rawilk** [comment]
In a release I'm working on, there will be a default export available as well.

 See: https://github.com/rawilk/vue-context/tree/release/v5

**Comment by rawilk** [comment]
Version 5.0.0 is available now, which should give you the ability to import a default export instead now.
