### ISSUE TITLE
Export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by kilkujadek** [rawilk/vue-context#44]
I'm building little app in meteor+vue.js. As soon as I add 

`import { VueContext } from 'vue-context'; ` 

or

`import VueContext from 'vue-context';`

to component it start to crash with error message: 

`SyntaxError: export declarations may only appear at top level of a module`

Any way to fix it?

**Comment by rawilk** [comment]
I'm not sure. It's hard to say since anytime I've tried it with either way of importing it seems to work just fine. Unless someone else has this issue when using meteor & vue, I'm not really sure what to tell you.
