### ISSUE TITLE
Context menu can't be closed by click outside menu and shown in wrong place

### ISSUE THREAD

**Issue by it-sha** [rawilk/vue-context#45]
### Description

When UI element is draggable - context menu can't be closed by click outside menu and shown in wrong place.

### Steps to Reproduce

1. Right Mouse Click to open menu
2. mousedown outside menu, move, mouseup
3. The context menu is shown and placed in the wrong spot
Demo in video https://monosnap.com/file/YlyygeJbHYiGMxhA3gtSwZAn2fqRj1

**Expected behavior:**
The context menu is hidden

**Actual behavior:** 
The context menu is shown and placed in the wrong spot

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Version
5.0.0
Chrome 78.0.3904.108 64bit

**Comment by it-sha** [comment]
@rawilk, Is any way to avoid this bug?

**Comment by rawilk** [comment]
I'm not really sure. This is kind of an edge case and I think you'll probably need to implement some kind of logic on your end to handle it.

**Comment by GustavoMorais** [comment]
@it-sha I don't know if you still need it, but there is a library that can help with that
https://www.npmjs.com/package/vue-click-outside

@rawilk Take a look too, can be a good one to implement in this project
