### ISSUE TITLE
Doesn't work after upgrading to 5.0: vue-context.js?8c7c:206 Uncaught ReferenceError: Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by tangyuanxiaoniu** [rawilk/vue-context#46]
After upgrading from 4.1.0 to 5.0, VueContext doesn't work anymore.

The console shows the following error when loading the app:

vue-context.js?8c7c:206 Uncaught ReferenceError: Invalid left-hand side in assignment

**Comment by rawilk** [comment]
There's probably an issue with either your code or build process. I was able to import the menu into an empty project and use it just fine. The documentation site also imports the npm package version of it as well with no errors.
