### ISSUE TITLE
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'clientY' of undefined"

### ISSUE THREAD

**Issue by mewcrazy** [rawilk/vue-context#48]
Hello,

I can't get vue-context to work with buefy Table's. (buefy = bulma css framework for vue; https://github.com/buefy/buefy)

I get the following error:

[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'clientY' of undefined"

`<b-table
	:data="clients_filtered"
	:paginated="true"
	:per-page="perPage"
	:current-page.sync="currentPage"
	:pagination-simple="false"
	:pagination-position="'bottom'"
	:default-sort-direction="'asc'"
	@contextmenu="rightClickClient"
	sort-icon="caret-down"
	sort-icon-size="is-small"
	aria-current-label="Current page">
</b-table>`

And the function:

`rightClickClient: function(client, event) {
	event.preventDefault()
	this.$refs.menu.open()
}`

`<vue-context ref="menu">
	<li>
		<a href="#" @click.prevent="onClick($event.target.innerText)">Option 1</a>
	</li>
	<li>
		<a href="#" @click.prevent="onClick($event.target.innerText)">Option 2</a>
	</li>
</vue-context>`

**Comment by rawilk** [comment]
You have to make sure you pass the `event` through to the `open()` method as the first argument.
