### ISSUE TITLE
Context Menu stays open if you click in an iframe

### ISSUE THREAD

**Issue by Bommel24** [rawilk/vue-context#49]
# Description

Context-Menu won't close if you click on an iframe after you opened the Context-Menu.

### Steps to Reproduce

1. Open a context menu
2. Left click into an iframe
3. Watch the context menu not close

**Expected behavior: Close Context Menu

**Actual behavior: Context Menu stays open

**Reproduces how often: 100%
### Version

^5.0.0
Electron

**Comment by rawilk** [comment]
I think that's kind of expected since an iframe has its own DOM. To be honest, this kind of sounds like an edge case. I think you could probably add a click event handler to the iframe and manually close the context menu, but I don't think think there's much I can do on my end.
