### ISSUE TITLE
Sintax error in normalize-slot.js in IE 11

### ISSUE THREAD

**Issue by mwleinad** [rawilk/vue-context#53]
Getting a Syntax error (not a lot of information) in the line that contains this file.
vue-context/src/js/normalize-slot.js

Any idea why this might be happening?

We are using core-js as a polyfill for ES6

Thanks!

**Comment by rawilk** [comment]
Not sure. From what I can tell everything should be fine.

**Comment by lmkz** [comment]
Just had same issue; webpack only transpiles your own code by default, you have to tell it explicity to transpile ES6 (like vue-context) back to ES5.  See here for how to enable: https://stackoverflow.com/questions/52615179/vue-cli-3-does-not-convert-vendors-to-es5
