### ISSUE TITLE
Vue global install not support.

### ISSUE THREAD

**Issue by liudonghua123** [rawilk/vue-context#54]
### Description

I tried to install it globally in main.js like this.
```
import { VueContext } from 'vue-context';
Vue.use(VueContext);
```

### Steps to Reproduce

1. install globally as above.
2. add the following vue-context in the template 

```
<vue-context ref="menu">
            <li>
              <a href="#" @click.prevent="onClick($event.target.innerText)">Option 1</a>
            </li>
            <li>
              <a href="#" @click.prevent="onClick($event.target.innerText)">Option 2</a>
            </li>
          </vue-context>
```

**Expected behavior:** [What did you expect to happen]
The vue-context did not render correctly.

**Actual behavior:** [What actually happens]
The vue-context should render correctly.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Version
^5.1.0

**Comment by liudonghua123** [comment]
It can only install in old methods like `Vue.component('VueContext', VueContext);`.

**Comment by rawilk** [comment]
It's not exported as a plugin, so that won't work. If you use `Vue.component('vue-context', VueContext);` instead, it should work for you globally.

**Comment by rawilk** [comment]
> It can only install in old methods like `Vue.component('VueContext', VueContext);`

That's not an "old" method and is still perfectly valid for registering components globally, which is what the context menu is. It's **not** a plugin, which is what Vue.use() is for.

**Comment by liudonghua123** [comment]
It can only install in old methods like `Vue.component('VueContext', VueContext);`.
