### ISSUE TITLE
Documentation site is down? 

### ISSUE THREAD

**Issue by nachodd** [rawilk/vue-context#56]
I know that this it won't be the right place, sorry... but, is the documentation site down? it keeps on giving error 500
Thanks!

**Comment by rawilk** [comment]
I recently upgraded the server the documentation is on to PHP 7.4, so it must have broken something on there. I'll have to look into why it's not working.

**Comment by rawilk** [comment]
Doc site is back up now and is re-designed as well.

**Comment by nachodd** [comment]
Nice! Thanks! 👍

**Comment by nachodd** [comment]
Cool! Thanks! 👍
