### ISSUE TITLE
Its possible to open the context menu from children components?

### ISSUE THREAD

**Issue by Dagdelo** [rawilk/vue-context#58]
I have this scenario: component A has vue-context component. B is children from A, and have several other components (children of B), how to open context menu properly from an children of B? It is possible?

**Comment by davidchalifoux** [comment]
I would also like to know how to do this, did you figure it out @Dagdelo?

**Comment by Dagdelo** [comment]
@davidchalifoux I used the [open ](https://github.com/rawilk/vue-context/blob/master/src/js/vue-context.js#L219)method, accessing the instance of vue-context from the parent.
