### ISSUE TITLE
The menu is always on the screen when I hide an option (with v-if) and with some variable of the child array.

### ISSUE THREAD

**Issue by edwin2000** [rawilk/vue-context#6]

**Comment by edwin2000** [comment]
Hi, I trying to disable an option but I not found a way to do it, then I hide the option with v-if directive.
The problem is then that the context menu no disappear and the only option is to click on it.
Is there any way to disable an option? 
Thanks.

**Comment by rawilk** [comment]
There is more than likely something with your code that is causing this because with normal usage, the  menu does not behave like this. If you visit https://rawilk.github.io/vue-context you will be able to see this. 

I can't really help you unless you provide some code and more information on how you're using the menu. Please refer to the [issue template](https://github.com/rawilk/vue-context/blob/master/.github/ISSUE_TEMPLATE.md) for this.

**Comment by edwin2000** [comment]
Thanks Rawilk for you answer.

**Description**
The menu no disappear when I use the directive v-if and some variable of the child array.

**Steps to Reproduce**

        <p @contextmenu.prevent="$refs.menu.open($event, { foo: 'bar' })">
          Right click on me
        </p>

        <vue-context ref="menu">
            <ul slot-scope="child">
                <li @click="onClick($event.target.innerText, child.data)" **v-if="child.data.foo"**>Option 1</li>
                <li @click="onClick($event.target.innerText, child.data)">Option 2</li>
            </ul>
        </vue-context>


**Actual behavior:** The context menu no disappear

**Reproduces how often:** 100%

**Version**
Last

**Additional Information**

**Comment by rawilk** [comment]
@edwin2000 

Sorry for the delayed response. From what you've provided, it looks like it should work just fine. Maybe try this instead for the menu:

```html
<vue-context ref="menu">
    <ul slot-scope="child" v-if="child.data">
          <li @click="onClick($event.target.innerText, child.data)" v-if="child.data.foo">Option 1</li>
          ...
    </ul>
</vue-context>
```

Also, are you receiving any errors in the console? If so, that could possibly prevent the menu from closing.

**Comment by edwin2000** [comment]
Thanks @rawilk .
It works great now.

**Comment by rawilk** [comment]
Disabling an option really depends on your implementation of the menu since the menu does not know about its content.
