### ISSUE TITLE
How to adjust the menu (menu item) height?

### ISSUE THREAD

**Issue by mikeerickson** [rawilk/vue-context#63]
Using the latest version and menu appears just fine.  

However, I am trying to adjust the menu height (I guess more importantly the menu items)

**Comment by rawilk** [comment]
You should be able to add your own custom styles to the menu by adding them to a stylesheet **after** you import the menu's styles.

From what I understand, you probably just need to adjust the padding in the anchor tags on the menu in your use case:

When using Sass:
```sass
@import '~vue-context/src/sass/vue-context';

.v-context ul > li > a {
     padding: your custom padding here;
}
```
