### ISSUE TITLE
Vue 3 Support

### ISSUE THREAD

**Issue by jd-solanki** [rawilk/vue-context#68]
As Vue 3 has RC It will be a good idea to add support for Vue 3.

I haven't tested it yet but we will surely do it within a month so I wanted to know will this package get Vue 3 support?

**Comment by rawilk** [comment]
I do plan on adding support for vue 3 at some point. I'm not sure yet what that'll all involve, so I'm not sure when I'll be doing that yet.

**Comment by rawilk** [comment]
If anyone is willing to submit a PR on this to add support for vue 3, it'd be greatly appreciated. I can't really say when I'd get to it myself since I've switched to using a "TALL" stack, so I don't have much motivation to keep maintaining this package if I'm not using Vue anymore.
