### ISSUE TITLE
The nested menu is not visible in Safari/MacOS

### ISSUE THREAD

**Issue by ja6** [rawilk/vue-context#69]
### Description

The nested menu doesn't render on Safari/MacOS.

![nested-context-menu-on-safari](https://user-images.githubusercontent.com/6674959/93504368-ae2e7400-f919-11ea-87a0-1f61bdfa4c94.png)

### Steps to Reproduce

1. Open Safari browser (if you have an Apple device)
2. Visit the demo example: [https://randallwilk.dev/docs/vue-context/v6/demos/advanced#nested-menus](https://randallwilk.dev/docs/vue-context/v6/demos/advanced#nested-menus)
3. Try to open the nested menu.

**Expected behavior:** The nested menu is visible.

**Actual behavior:** Only the first (non-nested) menu is visible. The nested menu (the second one) is not visible, except a very tiny part of it, which seems to be the part of it that is overlapping with the first (non-nested) menu.

### Version

Seen in versions 5.2.0 and 6.0.0

Tested on:
- MacOS Catalina 10.15.6
- Safari 13.1.2

### Additional information

I unfortunately don't have a Mac myself that could possibly run Safari, so I can't really test and debug it myself, but I've added a screenshot.

**Comment by rawilk** [comment]
Hmm, I'm using Safari 14.0 on my iMac and it seems to be working fine, so maybe something changed in Safari since v13.1.2. I'm going to close this as it seems to be resolved with a newer browser version.

**Comment by ja6** [comment]
Great! I can confirm that it works now, using Safari 14.0.
