### ISSUE TITLE
Nested Menus Can't display properly in chrome 73

### ISSUE THREAD

**Issue by xuzhen1994** [rawilk/vue-context#71]
### Steps to Reproduce

1. I'm using the chrome 73 and Nested Menus Can't display properly
2. 
![image](https://user-images.githubusercontent.com/6793111/94252291-4e0d8280-ff56-11ea-8051-0c4904b10bbd.png)

### Version

"vue-context": "^6.0.0",

**Comment by xuzhen1994** [comment]
newest chrome 85 don't have this problem

**Comment by rawilk** [comment]
Closing this, as it works with the latest versions of browsers.
