### ISSUE TITLE
Native cut copy paste functions 

### ISSUE THREAD

**Issue by vikaskedia** [rawilk/vue-context#72]
Excellent work.

In the [open source EMR ](https://github.com/savantcare/emr) I am trying to integrate the vue-context.

Looking at the examples it seems I will loose the functionality of "cut" "copy" "paste" 

![image](https://user-images.githubusercontent.com/6703876/95325324-e14b8f80-0855-11eb-87b4-2cab14a9750d.png)

Is that correct ?

**Comment by rawilk** [comment]
Yes, you'll have to implement those kind of things yourself.
