### ISSUE TITLE
opening the menu on a regular click

### ISSUE THREAD

**Issue by Alex-front-end-developer** [rawilk/vue-context#76]
how can I open the menu by left-clicking, help me please?)

**Comment by rawilk** [comment]
If you haven't please refer to the docs for this, as it has been explained there. Relevant docs url: https://randallwilk.dev/docs/vue-context/v6/usage/advanced-usage#left-click

If you still need help after that, please refer to a similar issue regarding this: https://github.com/rawilk/vue-context/issues/20
